version: 2.1

orbs:
  localstack: localstack/platform@<< pipeline.parameters.dev-orb-version >>
  orb-tools: circleci/orb-tools@12.1.0
  bats: circleci/bats@1.1.0
  shellcheck: circleci/shellcheck@3.2.0

# Pipeline Parameters
parameters:
  run-integration-tests:
    description: An internal flag to prevent integration test from running before a development version has been created.
    type: boolean
    default: false
  dev-orb-version:
    description: >
      The development version of the orb to test.
      This value is automatically adjusted by the "trigger-integration-tests-workflow" job to correspond with the specific version created by the commit and should not be edited.
      A "dev:alpha" version must exist for the initial pipeline run.
    type: string
    default: "dev:alpha"

jobs:
  integration-test-1:
    executor: localstack/default
    steps:
      - checkout
      - localstack/startup
      - run:
          command: |
            which aws
            which awslocal
            awslocal s3 mb s3://test
            awslocal s3 ls

workflows:
  test-pack:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - shellcheck/check:
          dir: ./src/scripts
          exclude: SC2148
      - bats/run:
          path: ./src/tests
          exclude: RC010
      - orb-tools/publish:
          orb_name: localstack/platform
          vcs_type: gh
          # context: ctx1
          requires:
            - orb-tools/lint
            - orb-tools/pack
            - bats/run
            - shellcheck/check
      # Trigger an integration workflow to test the dev:${CIRCLE_SHA1:0:7} version of your orb
      - orb-tools/review:
          name: trigger-integration-dev
          # context: ctx1
          requires:
            - orb-tools/publish

  # This `integration-test_deploy` workflow will only run
  # when the run-integration-tests pipeline parameter is set to true.
  # It is meant to be triggered by the "trigger-integration-tests-workflow"
  # job, and run tests on <your orb>@dev:${CIRCLE_SHA1:0:7}.
  integration-test_deploy:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      # Run any integration tests defined within the `jobs` key.
      - integration-test-1
      # Publish a semver version of the orb. relies on
      # the commit subject containing the text "[semver:patch|minor|major|skip]"
      # as that will determine whether a patch, minor or major
      # version will be published or if publishing should
      # be skipped.
      # e.g. [semver:patch] will cause a patch version to be published.
      - orb-tools/publish:
          orb_name: localstack/platform
          vcs_type: gh
          # context: ctx1
          pub_type: production
          requires:
            - integration-test-1
          filters:
            branches:
              only:
                - master
                - main
