description: >
  LocalStack executor on Ubuntu VM using Docker

parameters:
  image:
    default: ubuntu-2204:2023.02.1
    description: Virtual machine image to use
    type: string

machine:
  image: '<<parameters.image>>'
