description: >
  LocalStack executor on Ubuntu VM using Docker

parameters:
  image:
    default: ubuntu-2004:202101-01
    description: Virtual machine image to use
    type: string

machine:
  image: '<<parameters.image>>'
